Reps-platform 2.0
ec-europa/ec-reps-platform pull request #2
Opened 2017-06-02 09:55 UTC by libetho

2017-06-14 09:21 UTC, iulianweb requested changes

2017-06-14 09:21 UTC, iulianweb commented on resources/reps-platform.make
> +projects[admin_theme][subdir] = "contrib"
Needs evaluation.

2017-06-14 09:21 UTC, iulianweb commented on resources/reps-platform.make
> +projects[administration_language_negotiation][subdir] = "contrib"
Needs evaluation.

2017-06-14 09:21 UTC, iulianweb commented on lib/modules/custom/mapeditor/ec_geocoder/.svn/all-wcprops
> +K 25
.svn folder should not be here.

2017-06-14 09:21 UTC, iulianweb commented
Also please fix all coding standard violations, see attached.
[reps_phpcs.txt](https://github.com/ec-europa/ec-reps-platform/files/1074106/reps_phpcs.txt)

2017-06-19 08:02 UTC, libetho commented on resources/reps-platform.make
> +projects[admin_theme][subdir] = "contrib"
Removed (not used anymore)

2017-06-19 08:04 UTC, libetho commented on resources/reps-platform.make
> +projects[administration_language_negotiation][subdir] = "contrib"
https://webgate.ec.europa.eu/CITnet/jira/browse/NEMA-358

2017-06-19 16:27 UTC, iulianweb commented on resources/reps-platform.make
> +projects[administration_language_negotiation][subdir] = "contrib"
I don't see any proof that someone from the QA team approved this contrib and I am not saying this contrib is not OK...

2017-06-20 09:08 UTC, iulianweb commented
Please fix all coding standard violations:
[reps_phpcs_2.txt](https://github.com/ec-europa/ec-reps-platform/files/1087573/reps_phpcs_2.txt)

2017-06-21 08:22 UTC, libetho commented
Hi @iulianweb 

Regarding coding standards to fix:
- **reps_admin**: The problematic value is not prefixed by reps_admin because I'm getting de value previously declared in the parent module: reps_core
- **reps_migrate**: I don't think that the remaining issue are blocking because these class are called in country specif modules and all these modules are already deployed. The goal by keeping reps_migrate for the moment is to uninstall it in a clean way as you can see in my update in reps_core.
- **mbp_sync**: this module is developed by @drishu but he is on holidays for the moment. I don't know how I can fix this. If you can help me for this i should be great (I'm available on Lync).

In advance for you help!
[cs-review.txt](https://github.com/ec-europa/ec-reps-platform/files/1090765/cs-review.txt)

2017-06-21 13:31 UTC, iulianweb commented
Hi @libetho 
OK for reps_admin, reps_migrate, mbp_sync. False positive should be excluded in the resources/phpcs-custom.xml.
As agreed please go back to the approved module. It seems there are some issues https://webgate.ec.europa.eu/CITnet/jira/browse/REPR-472

2017-06-21 13:34 UTC, iulianweb commented on lib/features/reps_core/reps_core.install
> + * - nexteuropa_metatags
Please add rabbit_hole in this list too.

2017-06-21 14:28 UTC, libetho commented
Hi @iulianweb ,

Everything should be ok.
Thank for the work and don't hesitate if you have any additional remarks

Regards

2017-06-22 09:23 UTC, merged